version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: himansh007/stamurai
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=himanshuser
      - MYSQL_PASS=himanshpass
      - MYSQL_DB=stamurai
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:3000"
    container_name: stamurai
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=himanshuser
      - MYSQL_PASSWORD=himanshpass 
      - MYSQL_DATABASE=stamurai
    container_name: stamurai-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: stamurai-phpmyadmin-app
  redis:
    image: "redis:alpine"

    command: redis-server

    ports:
     - "6379:6379"

    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master

    networks:
      node_net:
        ipv4_address: 172.28.1.4

networks:
  frontend:
  backend:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16